#pragma once

#include "Logger.h"

enum Logger::Tag {
	DEBUG    = 0b00000001,
	ERR      = 0b00000010,
	WARN     = 0b00000100,
	ASSERT   = 0b00001000,
	INFO     = 0b00010000
};

enum Logger::ForegroundColor {
	/* 0 */ FG_BLACK		= 0,
	/* 1 */ FG_DK_BLUE		= FOREGROUND_BLUE,
	/* 2 */ FG_DK_GREEN		= FOREGROUND_GREEN,
	/* 3 */ FG_DK_CYAN		= FOREGROUND_BLUE | FOREGROUND_GREEN,
	/* 4 */ FG_DK_RED		= FOREGROUND_RED,
	/* 5 */ FG_PURPLE		= FOREGROUND_BLUE | FOREGROUND_RED,
	/* 6 */ FG_DK_YELLOW	= FOREGROUND_RED | FOREGROUND_GREEN,
	/* 7 */ FG_LT_GRAY		= FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED,
	/* 8 */ FG_DK_GRAY		= FOREGROUND_INTENSITY,
	/* 9 */ FG_BLUE			= FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	/* a */ FG_GREEN		= FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	/* b */ FG_CYAN			= FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	/* c */ FG_RED			= FOREGROUND_RED | FOREGROUND_INTENSITY,
	/* d */ FG_MAGENTA		= FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY,
	/* e */ FG_YELLOW		= FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	/* f */ FG_WHITE		= FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY
};

enum Logger::BackgroundColor {
	/* 0 */ BG_BLACK		= 0,
	/* 1 */ BG_DK_BLUE		= BACKGROUND_BLUE,
	/* 2 */ BG_DK_GREEN		= BACKGROUND_GREEN,
	/* 3 */ BG_DK_CYAN		= BACKGROUND_BLUE | BACKGROUND_GREEN,
	/* 4 */ BG_DK_RED		= BACKGROUND_RED,
	/* 5 */ BG_PURPLE		= BACKGROUND_BLUE | BACKGROUND_RED,
	/* 6 */ BG_DK_YELLOW	= BACKGROUND_RED | BACKGROUND_GREEN,
	/* 7 */ BG_LT_GRAY		= BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED,
	/* 8 */ BG_DK_GRAY		= BACKGROUND_INTENSITY,
	/* 9 */ BG_BLUE			= BACKGROUND_BLUE | BACKGROUND_INTENSITY,
	/* a */ BG_GREEN		= BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	/* b */ BG_CYAN			= BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	/* c */ BG_RED			= BACKGROUND_RED | BACKGROUND_INTENSITY,
	/* d */ BG_MAGENTA		= BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY,
	/* e */ BG_YELLOW		= BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
	/* f */ BG_WHITE		= BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY
};